// Normalize Balance Transactions
// New map step after the Shopify balanceTransactions action.
// Groups Shopify Payments balance transactions by associated order.
//
// Replace REPLACE_WITH_FETCH_BALANCE_TRANSACTIONS_STEP_KEY with the new Shopify
// step key generated by Gravity.

const payoutData = (input["mapPV2R"] || [])[0] || {};
const rawResponse = (input["REPLACE_WITH_FETCH_BALANCE_TRANSACTIONS_STEP_KEY"] || [])[0] || {};

const transactionConnection = rawResponse?.shopifyPaymentsAccount?.balanceTransactions || {};
const edges = transactionConnection.edges || [];
const nodes = transactionConnection.nodes || [];
const pageInfo = transactionConnection.pageInfo || {};
const rawTransactions = edges.length > 0
  ? edges.map(edge => edge.node).filter(Boolean)
  : nodes.filter(Boolean);

const roundMoney = (n) => Math.round(Number(n || 0) * 100) / 100;

if (pageInfo.hasNextPage) {
  throw new Error(
    `Balance transactions for payout ${payoutData.payoutId} exceed 250 records; add pagination before creating the Journal Entry`
  );
}

const payoutGid = payoutData.payoutGid || null;

const payoutTransactions = rawTransactions.filter(tx => {
  if (tx.test === true) {
    throw new Error(`Test balance transaction ${tx.id} returned for payout ${payoutData.payoutId}`);
  }

  if (tx.type === "TRANSFER" || tx.type === "TRANSFER_FAILURE") {
    return false;
  }

  if (payoutGid && tx.associatedPayout?.id && tx.associatedPayout.id !== payoutGid) {
    return false;
  }

  return true;
});

if (payoutTransactions.length === 0) {
  throw new Error(`No Shopify Payments balance transactions found for payout ${payoutData.payoutId}`);
}

const groupMap = new Map();

function getGroupKey(tx) {
  if (tx.associatedOrder?.id) {
    return `order:${tx.associatedOrder.id}`;
  }

  const type = tx.type || "UNKNOWN";
  const reason = tx.adjustmentReason || "none";
  return `non_order:${type}:${reason}`;
}

function getGroupSeed(tx) {
  if (tx.associatedOrder?.id) {
    return {
      orderId: tx.associatedOrder.id,
      orderName: tx.associatedOrder.name || tx.associatedOrder.id,
      isNonOrderAdjustment: false,
      adjustmentReason: null
    };
  }

  const adjustmentName = (tx.adjustmentsOrders || [])[0]?.name || null;
  const reason = tx.adjustmentReason || tx.type || "Non-order adjustment";

  return {
    orderId: null,
    orderName: adjustmentName || "Non-order adjustment",
    isNonOrderAdjustment: true,
    adjustmentReason: reason
  };
}

for (const tx of payoutTransactions) {
  const key = getGroupKey(tx);
  const seed = getGroupSeed(tx);

  if (!groupMap.has(key)) {
    groupMap.set(key, {
      ...seed,
      grossAmount: 0,
      feeAmount: 0,
      netAmount: 0,
      transactionIds: [],
      transactionTypes: []
    });
  }

  const group = groupMap.get(key);
  const grossAmount = Number(tx.amount?.amount || 0);
  const feeAmount = Number(tx.fee?.amount || 0);
  const netAmount = Number(tx.net?.amount || 0);

  group.grossAmount = roundMoney(group.grossAmount + grossAmount);
  group.feeAmount = roundMoney(group.feeAmount + feeAmount);
  group.netAmount = roundMoney(group.netAmount + netAmount);
  group.transactionIds.push(tx.id);

  if (tx.type && !group.transactionTypes.includes(tx.type)) {
    group.transactionTypes.push(tx.type);
  }
}

const orderGroups = Array.from(groupMap.values());
const orderCount = orderGroups.filter(group => !group.isNonOrderAdjustment).length;
const nonOrderAdjustmentCount = orderGroups.filter(group => group.isNonOrderAdjustment).length;

const grossTotal = roundMoney(orderGroups.reduce((sum, group) => sum + Number(group.grossAmount || 0), 0));
const feeTotal = roundMoney(orderGroups.reduce((sum, group) => sum + Number(group.feeAmount || 0), 0));
const transactionNetTotal = roundMoney(orderGroups.reduce((sum, group) => sum + Number(group.netAmount || 0), 0));
const payoutNetAmount = roundMoney(payoutData.netAmount);
const payoutNetDifference = roundMoney(transactionNetTotal - payoutNetAmount);

return [{
  ...payoutData,
  balanceTransactionCount: payoutTransactions.length,
  orderCount,
  nonOrderAdjustmentCount,
  orderGroups,
  grossTotal,
  feeTotal,
  transactionNetTotal,
  payoutNetDifference
}];
