// Calculate Order-Level Accounting Values
// Replaces the old payout-summary calculation.
// Builds one JE with order-level line groups: net, fee, clearing/gross offset.
//
// Replace REPLACE_WITH_NORMALIZE_BALANCE_TRANSACTIONS_STEP_KEY with the new map
// step key generated by Gravity.

const data = (input["REPLACE_WITH_NORMALIZE_BALANCE_TRANSACTIONS_STEP_KEY"] || [])[0] || {};
const orderGroups = data.orderGroups || [];

const roundMoney = (n) => Math.round(Number(n || 0) * 100) / 100;

function toJournalLine(account, signedAmount, memo, extra) {
  const amount = roundMoney(Math.abs(Number(signedAmount || 0)));
  if (amount === 0) return null;

  if (signedAmount >= 0) {
    return { account, debit: amount, memo, ...(extra || {}) };
  }

  return { account, credit: amount, memo, ...(extra || {}) };
}

if (orderGroups.length === 0) {
  throw new Error(`No order-level groups available for payout ${data.payoutId}`);
}

const lines = [];

for (const group of orderGroups) {
  const memo = group.isNonOrderAdjustment
    ? `Shopify payout ${data.payoutId} - Non-order adjustment`
    : `Shopify payout ${data.payoutId} - Order ${group.orderName}`;

  const commonExtra = {
    division: data.storeConfig?.division,
    orderId: group.orderId || null,
    orderName: group.orderName || null,
    transactionIds: group.transactionIds || [],
    isNonOrderAdjustment: group.isNonOrderAdjustment === true
  };

  const netLine = toJournalLine("1113", group.netAmount, memo, commonExtra);
  const feeLine = toJournalLine("471", group.feeAmount, memo, {
    ...commonExtra,
    department: "11"
  });
  const clearingLine = toJournalLine("1114", -Number(group.grossAmount || 0), memo, commonExtra);

  if (netLine) lines.push(netLine);
  if (feeLine) lines.push(feeLine);
  if (clearingLine) lines.push(clearingLine);
}

const totalDebits = roundMoney(lines.reduce((sum, line) => sum + Number(line.debit || 0), 0));
const totalCredits = roundMoney(lines.reduce((sum, line) => sum + Number(line.credit || 0), 0));
const isBalanced = totalDebits === totalCredits;
const payoutNetDifference = roundMoney(data.payoutNetDifference || 0);

if (Math.abs(payoutNetDifference) > 0.01) {
  throw new Error(
    `Order-level net total does not match payout ${data.payoutId}: difference ${payoutNetDifference}`
  );
}

if (!isBalanced) {
  throw new Error(
    `Unbalanced journal entry for payout ${data.payoutId}: debits ${totalDebits}, credits ${totalCredits}`
  );
}

return [{
  ...data,
  feeTotal: roundMoney(data.feeTotal),
  clearingAmount: roundMoney(Math.abs(data.grossTotal)),
  clearingSignedAmount: roundMoney(-Number(data.grossTotal || 0)),
  lines,
  totalDebits,
  totalCredits,
  isBalanced
}];
