// NetSuite: Update Sales Orders Reconciliation Field
// New NetSuite Execute Custom Code step after "Map - Build Sales Order Reconciliation Payload".
//
// Replace REPLACE_WITH_BUILD_CASH_SALE_RECON_PAYLOAD_STEP_KEY with the map step
// key generated by Gravity.

const payload = ${JSON.stringify(input?.mapQKUQ?.[0])};

function uniqueStrings(values) {
  const seen = {};
  const output = [];

  for (let i = 0; i < values.length; i++) {
    const value = values[i] !== null && values[i] !== undefined ? String(values[i]).trim() : '';
    if (!value || seen[value]) continue;
    seen[value] = true;
    output.push(value);
  }

  return output;
}

function orderNameCandidates(orderName) {
  const raw = String(orderName || '').trim();
  return uniqueStrings([raw]);
}

function execute() {
  const results = {
    success: false,
    payoutId: payload?.payoutId || null,
    externalId: payload?.externalId || null,
    journalEntryId: payload?.journalEntryId || null,
    journalEntryNumber: payload?.journalEntryNumber || null,
    reconciliationDate: payload?.reconciliationDate || null,
    reconciliationValue: payload?.reconciliationValue || null,
    requestedOrderCount: 0,
    salesOrdersMatched: 0,
    salesOrdersUpdated: 0,
    salesOrdersMissing: [],
    updatedSalesOrders: [],
    searchAttempts: [],
    errors: [],
    salesOrderUpdateStatus: 'failed',

    // Backward-compatible aliases for the existing log step.
    cashSalesMatched: 0,
    cashSalesUpdated: 0,
    cashSalesMissing: [],
    updatedCashSales: [],
    cashSaleUpdateStatus: 'failed'
  };

  try {
    if (!payload) {
      throw new Error('Missing payload for Sales Order reconciliation update');
    }

    const orderNames = uniqueStrings(payload.orderNames || []);
    const reconciliationValue = payload.reconciliationValue;
    const targetFieldId = payload.salesOrderTargetFieldId || payload.cashSaleTargetFieldId || 'custbody_shopify_pymt_recon';
    const shopifyOrderIdFieldId = payload.shopifyOrderIdFieldId || 'custbody_shopify_ord_id';

    results.requestedOrderCount = orderNames.length;

    if (!reconciliationValue) {
      throw new Error('Missing reconciliationValue for Sales Order update');
    }

    if (orderNames.length === 0) {
      throw new Error('Missing orderNames for Sales Order update');
    }

    const SEARCH_CANDIDATE_CHUNK_SIZE = 75;
    const candidateToOrderNames = {};
    const matchedOrderNames = {};
    const matchedSalesOrdersById = {};
    const allCandidates = [];

    for (let orderIdx = 0; orderIdx < orderNames.length; orderIdx++) {
      const orderName = orderNames[orderIdx];
      const candidates = orderNameCandidates(orderName);

      for (let candidateIdx = 0; candidateIdx < candidates.length; candidateIdx++) {
        const candidate = candidates[candidateIdx];

        if (!candidateToOrderNames[candidate]) {
          candidateToOrderNames[candidate] = [];
          allCandidates.push(candidate);
        }

        candidateToOrderNames[candidate].push(orderName);
      }
    }

    function chunkArray(values, size) {
      const chunks = [];
      for (let i = 0; i < values.length; i += size) {
        chunks.push(values.slice(i, i + size));
      }
      return chunks;
    }

    function buildCandidateFilterExpression(candidates) {
      const expression = [];

      for (let i = 0; i < candidates.length; i++) {
        if (i > 0) {
          expression.push('OR');
        }
        expression.push([shopifyOrderIdFieldId, search.Operator.IS, candidates[i]]);
      }

      return expression.length === 1 ? expression[0] : expression;
    }

    function findSalesOrdersForCandidates(candidates, chunkIndex) {
      const candidateFilterExpression = buildCandidateFilterExpression(candidates);
      let matchedInChunk = 0;

      const salesOrderSearch = search.create({
        type: search.Type.SALES_ORDER,
        filters: [
          ['mainline', search.Operator.IS, 'T'],
          'AND',
          candidateFilterExpression
        ],
        columns: [
          search.createColumn({ name: 'internalid' }),
          search.createColumn({ name: 'tranid' }),
          search.createColumn({ name: shopifyOrderIdFieldId })
        ]
      });

      const pagedResults = salesOrderSearch.runPaged({ pageSize: 1000 });

      pagedResults.pageRanges.forEach(function(pageRange) {
        const page = pagedResults.fetch({ index: pageRange.index });

        page.data.forEach(function(result) {
          const salesOrderId = result.getValue({ name: 'internalid' });
          const salesOrderTranId = result.getValue({ name: 'tranid' });
          const matchedValue = String(result.getValue({ name: shopifyOrderIdFieldId }) || '').trim();
          const sourceOrderNames = candidateToOrderNames[matchedValue] || [];

          if (!salesOrderId || matchedSalesOrdersById[salesOrderId]) {
            return;
          }

          for (let i = 0; i < sourceOrderNames.length; i++) {
            matchedOrderNames[sourceOrderNames[i]] = true;
          }

          matchedSalesOrdersById[salesOrderId] = {
            orderName: sourceOrderNames[0] || matchedValue,
            matchedValue,
            salesOrderId,
            salesOrderTranId
          };

          matchedInChunk++;
        });
      });

      results.searchAttempts.push({
        strategy: 'salesOrder.' + shopifyOrderIdFieldId + '.chunkedOr',
        chunkIndex,
        candidateCount: candidates.length,
        matchedSalesOrderCount: matchedInChunk
      });
    }

    const candidateChunks = chunkArray(allCandidates, SEARCH_CANDIDATE_CHUNK_SIZE);

    for (let chunkIdx = 0; chunkIdx < candidateChunks.length; chunkIdx++) {
      try {
        findSalesOrdersForCandidates(candidateChunks[chunkIdx], chunkIdx + 1);
      } catch (error) {
        results.errors.push({
          orderName: null,
          message: 'Failed Sales Order chunk search ' + (chunkIdx + 1) + ': ' +
            (error && error.message ? error.message : String(error))
        });
      }
    }

    const matchedSalesOrders = [];
    for (const salesOrderId in matchedSalesOrdersById) {
      if (Object.prototype.hasOwnProperty.call(matchedSalesOrdersById, salesOrderId)) {
        matchedSalesOrders.push(matchedSalesOrdersById[salesOrderId]);
      }
    }

    for (let i = 0; i < matchedSalesOrders.length; i++) {
      const matchedSalesOrder = matchedSalesOrders[i];
      const values = {};
      values[targetFieldId] = reconciliationValue;

      try {
        record.submitFields({
          type: record.Type.SALES_ORDER,
          id: matchedSalesOrder.salesOrderId,
          values,
          options: {
            enableSourcing: false,
            ignoreMandatoryFields: true
          }
        });

        results.salesOrdersMatched++;
        results.salesOrdersUpdated++;
        results.updatedSalesOrders.push(matchedSalesOrder);
      } catch (error) {
        results.errors.push({
          orderName: matchedSalesOrder.orderName || null,
          salesOrderId: matchedSalesOrder.salesOrderId,
          message: error && error.message ? error.message : String(error)
        });
      }
    }

    for (let orderIdx = 0; orderIdx < orderNames.length; orderIdx++) {
      const orderName = orderNames[orderIdx];
      if (!matchedOrderNames[orderName]) {
        results.salesOrdersMissing.push(orderName);
      }
    }

    results.salesOrderUpdateStatus = results.errors.length > 0
      ? 'failed'
      : results.salesOrdersMissing.length > 0
        ? 'partial'
        : 'updated';

    results.cashSalesMatched = results.salesOrdersMatched;
    results.cashSalesUpdated = results.salesOrdersUpdated;
    results.cashSalesMissing = results.salesOrdersMissing;
    results.updatedCashSales = results.updatedSalesOrders;
    results.cashSaleUpdateStatus = results.salesOrderUpdateStatus;

    if (results.salesOrdersUpdated === 0) {
      throw new Error(
        'No Sales Orders were updated for payout ' +
        (payload.payoutId || 'unknown') +
        '. Missing orders: ' +
        results.salesOrdersMissing.join(', ')
      );
    }

    results.success = results.salesOrderUpdateStatus !== 'failed';
    return results;

  } catch (error) {
    results.success = false;
    results.salesOrderUpdateStatus = 'failed';
    results.cashSaleUpdateStatus = 'failed';
    results.message = error && error.message ? error.message : String(error);
    results.errors.push({
      orderName: null,
      message: results.message
    });
    return results;
  }
}

execute();
