// NetSuite: Update Sales Orders Reconciliation Field
// New NetSuite Execute Custom Code step after "Map - Build Sales Order Reconciliation Payload".
//
// Replace REPLACE_WITH_BUILD_CASH_SALE_RECON_PAYLOAD_STEP_KEY with the map step
// key generated by Gravity.

const payload = ${JSON.stringify(input?.REPLACE_WITH_BUILD_CASH_SALE_RECON_PAYLOAD_STEP_KEY?.[0])};

function uniqueStrings(values) {
  const seen = {};
  const output = [];

  for (let i = 0; i < values.length; i++) {
    const value = values[i] !== null && values[i] !== undefined ? String(values[i]).trim() : '';
    if (!value || seen[value]) continue;
    seen[value] = true;
    output.push(value);
  }

  return output;
}

function orderNameCandidates(orderName) {
  const raw = String(orderName || '').trim();
  const withoutHash = raw.replace(/^#/, '');
  return uniqueStrings([raw, withoutHash]);
}

function execute() {
  const results = {
    success: false,
    payoutId: payload?.payoutId || null,
    externalId: payload?.externalId || null,
    journalEntryId: payload?.journalEntryId || null,
    journalEntryNumber: payload?.journalEntryNumber || null,
    reconciliationDate: payload?.reconciliationDate || null,
    reconciliationValue: payload?.reconciliationValue || null,
    requestedOrderCount: 0,
    salesOrdersMatched: 0,
    salesOrdersUpdated: 0,
    salesOrdersMissing: [],
    updatedSalesOrders: [],
    searchAttempts: [],
    errors: [],
    salesOrderUpdateStatus: 'failed',

    // Backward-compatible aliases for the existing log step.
    cashSalesMatched: 0,
    cashSalesUpdated: 0,
    cashSalesMissing: [],
    updatedCashSales: [],
    cashSaleUpdateStatus: 'failed'
  };

  try {
    if (!payload) {
      throw new Error('Missing payload for Sales Order reconciliation update');
    }

    const orderNames = uniqueStrings(payload.orderNames || []);
    const reconciliationValue = payload.reconciliationValue;
    const targetFieldId = payload.salesOrderTargetFieldId || payload.cashSaleTargetFieldId || 'custbody_shopify_pymt_recon';
    const shopifyOrderIdFieldId = payload.shopifyOrderIdFieldId || 'custbody_shopify_ord_id';

    results.requestedOrderCount = orderNames.length;

    if (!reconciliationValue) {
      throw new Error('Missing reconciliationValue for Sales Order update');
    }

    if (orderNames.length === 0) {
      throw new Error('Missing orderNames for Sales Order update');
    }

    const updatedSalesOrderIds = {};

    function updateSalesOrderResult(result, orderName, candidate) {
      const salesOrderId = result.getValue({ name: 'internalid' });
      const salesOrderTranId = result.getValue({ name: 'tranid' });

      if (!salesOrderId || updatedSalesOrderIds[salesOrderId]) {
        return true;
      }

      const values = {};
      values[targetFieldId] = reconciliationValue;

      record.submitFields({
        type: record.Type.SALES_ORDER,
        id: salesOrderId,
        values,
        options: {
          enableSourcing: false,
          ignoreMandatoryFields: true
        }
      });

      updatedSalesOrderIds[salesOrderId] = true;
      results.salesOrdersMatched++;
      results.salesOrdersUpdated++;
      results.updatedSalesOrders.push({
        orderName,
        matchedValue: candidate,
        salesOrderId,
        salesOrderTranId
      });

      return true;
    }

    function searchAndUpdateSalesOrders(orderName, candidate) {
      let found = false;

      const salesOrderSearch = search.create({
        type: search.Type.SALES_ORDER,
        filters: [
          search.createFilter({
            name: 'mainline',
            operator: search.Operator.IS,
            values: 'T'
          }),
          search.createFilter({
            name: shopifyOrderIdFieldId,
            operator: search.Operator.IS,
            values: candidate
          })
        ],
        columns: [
          search.createColumn({ name: 'internalid' }),
          search.createColumn({ name: 'tranid' })
        ]
      });

      salesOrderSearch.run().each(function(result) {
        found = true;
        return updateSalesOrderResult(result, orderName, candidate);
      });

      return found;
    }

    function tryCandidate(orderName, candidate) {
      try {
        const found = searchAndUpdateSalesOrders(orderName, candidate);
        results.searchAttempts.push({
          orderName,
          candidate,
          strategy: 'salesOrder.' + shopifyOrderIdFieldId,
          found
        });
        return found;
      } catch (error) {
        results.searchAttempts.push({
          orderName,
          candidate,
          strategy: 'salesOrder.' + shopifyOrderIdFieldId,
          found: false,
          error: error && error.message ? error.message : String(error)
        });
        return false;
      }
    }

    for (let orderIdx = 0; orderIdx < orderNames.length; orderIdx++) {
      const orderName = orderNames[orderIdx];
      const candidates = orderNameCandidates(orderName);
      let matchedForOrder = false;

      for (let candidateIdx = 0; candidateIdx < candidates.length; candidateIdx++) {
        const candidate = candidates[candidateIdx];
        matchedForOrder = tryCandidate(orderName, candidate) || matchedForOrder;
      }

      if (!matchedForOrder) {
        results.salesOrdersMissing.push(orderName);
      }
    }

    results.salesOrderUpdateStatus = results.errors.length > 0
      ? 'failed'
      : results.salesOrdersMissing.length > 0
        ? 'partial'
        : 'updated';

    results.cashSalesMatched = results.salesOrdersMatched;
    results.cashSalesUpdated = results.salesOrdersUpdated;
    results.cashSalesMissing = results.salesOrdersMissing;
    results.updatedCashSales = results.updatedSalesOrders;
    results.cashSaleUpdateStatus = results.salesOrderUpdateStatus;

    if (results.salesOrdersUpdated === 0) {
      throw new Error(
        'No Sales Orders were updated for payout ' +
        (payload.payoutId || 'unknown') +
        '. Missing orders: ' +
        results.salesOrdersMissing.join(', ')
      );
    }

    results.success = results.salesOrderUpdateStatus !== 'failed';
    return results;

  } catch (error) {
    results.success = false;
    results.salesOrderUpdateStatus = 'failed';
    results.cashSaleUpdateStatus = 'failed';
    results.message = error && error.message ? error.message : String(error);
    results.errors.push({
      orderName: null,
      message: results.message
    });
    return results;
  }
}

execute();
